import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

Map<String, IconData> amenityIcons = {
  'kafe': Icons.local_cafe,
  'büfe': Icons.fastfood,
  'restoran': Icons.restaurant,
  'otopark': Icons.local_parking,
  'atm': Icons.local_atm,
  'üniversite': Icons.school,
  'spor tesisi': Icons.sports_soccer,
  'avm': Icons.local_mall,
  'market': Icons.local_grocery_store,
  'banka': Icons.account_balance,
  'sinema': Icons.local_movies,
  'wifi': Icons.wifi,
  'kuaför': Icons.cut,
  'otobüs durağı': Icons.directions_bus,
  'otel': Icons.hotel,
  'havaalanı': Icons.local_airport,
  'metro': Icons.subway,
  'tiyatro': Icons.theaters,
  'taksi durağı': Icons.local_taxi,
  'cami': Icons.mosque,
  'kilise': Icons.church,
  'sinegog': Icons.synagogue,
  'hastane': Icons.local_hospital,
  'metrobüs durağı': Icons.directions_bus,
  'stadyum': Icons.stadium,
  'vapur iskelesi': Icons.directions_boat,
  'izban': Icons.train,
  'benzinlik': Icons.local_gas_station,
  'dinlenme tesisi': Icons.local_parking,
  'sanayi': Icons.domain,
  'rent-a-car': Icons.directions_car,
  'spa': Icons.spa,
  'fabrika': Icons.factory,
  'otobüs terminali': Icons.directions_bus,
  'açık otopark': Icons.local_parking,
  'ptt': Icons.local_post_office,
  'cafe': Icons.coffee,
  'eczane': Icons.local_pharmacy,
  'park': Icons.local_parking,
  'resturant': Icons.restaurant,
  'metrobüs': Icons.directions_bus,
  'otobüs': Icons.directions_bus,
  'oto galeri': Icons.car_crash_outlined,
  'müze': Icons.museum,
  'benzin istasyonu': Icons.local_gas_station,
  'sanayi sitesi': Icons.domain,
  'okul': Icons.school,
  'mağaza': Icons.store,
  'iş merkezi': Icons.business,
  'metro durağı': Icons.train,
  'oto sanayi': FontAwesomeIcons.industry,
  'araç muayene istasyonu': Icons.directions_car,
  'spor salonu': Icons.sports,
  'adliye': Icons.account_balance,
  'postane': Icons.local_post_office,
  'kültür merkezi': Icons.museum,
  'çay bahçesi': Icons.local_cafe,
  'huzurevi': Icons.home,
  'itfaiye': Icons.local_fire_department,
  'otogar': Icons.directions_bus,
  'sanayi ve ticaret bakanlığı': Icons.domain,
  'konut': Icons.home,
  'akaryakıt istasyonu': Icons.local_gas_station,
  'pastane': Icons.restaurant,
  'aqua park': Icons.pool,
  'marina': Icons.directions_boat,
  'noter': Icons.note,
  'oto yıkama': Icons.local_car_wash,
  'kütüphane': Icons.local_library,
  'adalet sarayı': Icons.account_balance,
  'bar': Icons.local_bar,
  'pansiyon': Icons.hotel,
  'petshop': Icons.pets,
  'oto lastik': Icons.local_car_wash,
  'bezin istasyonu': Icons.local_gas_station,
  'araç servisi': Icons.local_car_wash,
  'kasap': Icons.local_grocery_store,
  'oto servis': Icons.local_car_wash,
  'iskele': Icons.directions_boat,
  'tren istasyonu': Icons.train,
  'tren garı': Icons.train,
  'akaryakı istasyonu': Icons.local_gas_station,
  'metro istasyonu': Icons.train,
  'tramvay durağı': Icons.train,
  'kargo': Icons.local_shipping,
  'otobüs garı': Icons.directions_bus,
  'n/a': Icons.error_outline,
  'resotran': Icons.restaurant,
  'yurt': Icons.hotel,
  'emniyet amirliği': Icons.local_police,
  'tramvay': Icons.train,
  'kayak merkezi': Icons.downhill_skiing,
  'retoran': Icons.restaurant,
  'sanayi ve ticaret odası': Icons.domain,
  'kafer': Icons.restaurant,
};
